---
output:
  html_document:
    css: www/styles.css
    anchor_sections: FALSE
    includes:
      in_header: "header_manual.html"

params:
  year_curr: 2024 # Current year of sampling
  all_years: TRUE # If FALSE, only reports on year_curr; TRUE reports on all years; not enabled yet- currently all years
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = FALSE, vline = "|")
options(knitr.kable.NA = '', scipen = 100)
```

## MacroPlot and Sample Event checks {.tabset .tabset-pills}
### MacroPlot Checks {.tabset}
```{r libs, include = F}
library(plantcomNGPN)
library(tidyverse) # dplyr, purrr, tidyr
library(knitr) # for kable and include_graphic()
library(kableExtra) # for custom kable features
library(sf) # for checking plot coords against park bounding boxes
library(data.table) # faster summarizing than dplyr for big datasets
library(DT) # much faster at making tables for large dfs than kable

all_years <- params$all_years
year_curr <- params$year_curr
year_range <- if(all_years == TRUE){2011:year_curr} else {year_curr}
year_hist <- 2011:(year_curr - 1)

```

```{r imports, include = F}
# If SQL setup:
importData(type = 'local',
           dbname = c("FFI_RA_AGFO", "FFI_RA_BADL", "FFI_RA_DETO", "FFI_RA_FOLA",
                      "FFI_RA_FOUS", "FFI_RA_JECA", "FFI_RA_KNRI", #"FFI_RA_MNRR",
                      "FFI_RA_MORU", "FFI_RA_SCBL", "FFI_RA_THRO", "FFI_RA_WICA"),
           keep_tables = T)
#keep_tables = T, export_views = T, export_path = "C:/temp")

# If SQL not set up, use import below instead, and update the import_path:
#importData(type = 'csv', import_path = "./data/NGPN_FFI_table_export_20250825.zip", keep_tables = T) 
#importData(type = 'csv', import_path = "./docs/data/NGPN_FFI_table_export_20250825.zip", keep_tables = T) 

```

```{r source, include = F}
# source code to generate most of the datasets/checks that are then printed in the rmd.
source("NGPN_network_MacroPlot_QC_compile.R")
#source("./docs/NGPN_network_QC_checks_compile.R")
```

#### Monitoring Status - SE {.tabset}
```{r monstat_park, eval = F}
df <- macro_samp2 |> filter(park %in% parkcode) |> 
  select(-park, -DefaultMonitoringStatus) |> 
  summarize(across(where(is.numeric), function(x){sum(x, na.rm = T)}), 
            .by = c(MacroPlot_Name, MacroPlot_Purpose)) |> 
  distinct()  
  
df[,3:ncol(df)][df[,3:ncol(df)] == 0] <- NA

yrs <- names(df[,grepl("yr", names(df))])

df$dup <- rowSums(df[,yrs] > 1, na.rm = T)


plot_mat <- 
kable(df |> select(-dup, -dup_ms), format = 'html', align = 'c',
      caption = paste0('Table 1. Matrix of NGPN PCM plots for **', parkcode, '** by monitoring status, purpose, and year sampled. ',
                       "Only plots with 'PCM' or 'RCM' in their name are included. ",
                       
                       "Values indicate the number of records for each plot, year for plots with Panel or
                       ForestStructure in their MacroPlot_Purpose, or MacroPlots with RCM in their name 
                       and blank MacroPlot_Purpose. ", 
                       "Values > 1 indicate duplicate sampling events in the SampleEvent table for that year and ",
                       "are highlighted <b style='background-color:#F2F2A0;'>yellow</b>. ",
                       "Duplicates within a year mean there are multiple dates and SampleEvent_GUIDs for a given year,
                       which is tricky to accommodate in table joins/analysis. It looks like these are plots that were 
                       started on one day and finished on another. It would be better to just use the first day and
                       SampleEvent in those cases.", "<br>","<br>",
                       
                       "Sampling schedule also does not exactly follow the 2 on 3 off, so Monitoring Status is not ",
                       "the only way to pull out NGPN PCM monitoring events?")) %>%
  kable_styling(fixed_thead = T, bootstrap_options = c("condensed", "striped"), 
                full_width = T, position = 'left', font_size = 10) %>%
  column_spec(1:(ncol(df)-2), border_left = "1px solid grey", border_right = "1px solid grey") %>%
  purrr::reduce(3:(ncol(df)-2), function(x, y){
    col = df[,y]
    column_spec(x, y, background = case_when(is.na(df[,y]) ~ "#ffffff",
                                             df[,y] == 1 ~ "#ffffff",
                                             df[,y] == 0 ~ "#ffffff",
                                             TRUE ~ "#F2F2A0"))}, .init = .) %>%
  #column_spec(1, background = ifelse(df$dup > 0, "#F2F2A0", "#ffffff")) %>%
  column_spec(1, background = case_when(#df$dup_ms > 1 ~ "orange",
                                        df$dup > 0 ~ "#F2F2A0", 
                                        TRUE ~ "white")) %>%
  #column_spec(3, background = ifelse(df$DefaultMonitoringStatus == "blank", "#AFAFAF", "white")) %>%
  collapse_rows(1, valign = "top")

print(plot_mat)
```

```{r, parktabs, results = 'asis'}
for(i in seq_along(park_list)){
  parkcode = park_list[[i]]
  cat("##### ", parkcode, "{.tabset}", "\n\n")
  <<monstat_park>>
  cat("\n\n")
  cat("\n\n")
}
```

#### Purpose {.tabset}
```{r purpose_park, include = F, eval = F}
df2 <- macro_purp |> mutate(park = substr(MacroPlot_Name, 1, 4)) |> filter(park == parkcode) |> select(-park)
nonvs <- names(macro_purp[!grepl("Panel|IM_Intensive", names(macro_purp))])
df2$nonvs <- rowSums(!is.na(df2[,nonvs]))
df3 <- df2 |> arrange(nonvs, MacroPlot_Name)

kbl_purpose <- kable(df3 |> select(-nonvs), 
                     format = 'html', align = 'c',
                     caption = paste0('Table 3. NGPN PCM plots by purpose in MacroPlot table. ', 
                                      'Only includes plots with "PCM" in the plot name, ',
                                      'which are assumed to be NGPN plant community monitoring plots.',
                                      " Plots that with a purpose other than Panel# or IM_Intensive are 
                                      highlighted <b style='background-color:#F2F2A0;'>yellow</b> 
                                      and sorted at the bottom.", 
                                      " Are the yellow plots NPGN plant community monitoring plots?", "<br>","<br>",
                                      " Unknown purpose indicates that field is blank for a given plot.",
                                      " Can the combination of Monitoring Status and Purpose be used to pull out",
                                      " NGPN PCM sampling events?")) %>% 
  kable_styling(fixed_thead = T, bootstrap_options = c("condensed", "striped"), 
                full_width = F, position = 'left', font_size = 10) %>%
  purrr::reduce(14:(ncol(df3)-1), function(x, y){
    col = df3[,y]
    column_spec(x, y, background = ifelse(is.na(col), "#ffffff", "#F2F2A0"))}, .init = .) %>%
  column_spec(1, background = ifelse(df3$nonvs == 1, "#ffffff", "#F2F2A0")) %>%
  column_spec(1:(ncol(df3)-1), border_left = "1px solid grey", border_right = "1px solid grey") #%>%
  #scroll_box(width = "500px", height = "800px", fixed_thead = TRUE)

print(kbl_purpose)
```


```{r, parktab3, results = 'asis'}
for(i in seq_along(park_list)){
  parkcode = park_list[[i]]
  cat("##### ", parkcode, "{.tabset}", "\n\n")
  <<purpose_park>>
  cat("\n\n")
  cat("\n\n")
}
```

